import React, { Component } from 'react';
import {
    View,
    Text,
    AsyncStorage,
    FlatList,
    TextInput,
    Image,TouchableOpacity,
    ActivityIndicator,
    ScrollView
} from 'react-native'


class DieuKhoan extends Component {
    
    constructor(props){
        super(props);

        
    }


    componentWillMount(){
        
    }


    render (){
        return (
            
            
           <ScrollView>
               <Text>VUI LÒNG ĐỌC KỸ CÁC ĐIỀU KHOẢN NÀY TRƯỚC KHI TRUY CẬP HOẶC SỬ DỤNG DỊCH VỤ.</Text>
                <Text style = {{marginHorizontal: 10}}>1. Quan hệ hợp đồng
                    Các Điều khoản Sử dụng này (“Điều khoản”) điều chỉnh việc bạn, một cá nhân, từ bất kỳ quốc gia nào trên thế giới truy cập hoặc sử dụng các ứng dụng, trang web, nội dung, sản phẩm và dịch vụ (“Dịch vụ”) của Công ty CP dịch vụ Tập Đoàn Việt ( VIGS GROUP), một công ty cổ phần thành lập ở Việt Nam, có văn phòng tại LK15, Phan Đình Giót, Văn Khê, Hà Đông, Hà Nội, Việt Nam, giấy phép đăng ký tại Sở Kế Hoạch và Đầu Tư số 0107450770 (“TOHOP”).
                    Việc tiếp cận và sử dụng các Dịch vụ của bạn đã cấu thành sự chấp nhận chịu sự ràng buộc của các Điều khoản này, sự ràng buộc này sẽ thiết lập mối quan hệ hợp đồng giữa bạn và TOHOP. Nếu bạn không đồng ý với các Điều khoản này, bạn sẽ không có quyền truy cập hoặc sử dụng các dịch vụ. Các Điều khoản này sẽ thay thế cho các thỏa thuận hoặc hợp đồng trước đây của bạn. TOHOP có thể ngay lập tức chấm dứt các Điều khoản này hoặc bất kỳ Dịch vụ nào liên quan đến bạn, hoặc nói chung là ngừng cung cấp hoặc từ chối quyền truy cập đến các Dịch vụ hoặc bất kỳ phần nào của dịch vụ, vào bất kỳ lúc nào vì bất kỳ lý do gì.
                    Các điều khoản bổ sung có thể được áp dụng cho các Dịch vụ nhất định, chẳng hạn như các chính sách cho một sự kiện, hoạt động hoặc khuyến mãi cụ thể, và các điều khoản bổ sung này sẽ được tiết lộ cho bạn liên quan đến các Dịch vụ được áp dụng. Các điều khoản bổ sung được thêm vào, và sẽ được coi là một phần của các Điều khoản dành cho các mục đích của Dịch vụ được áp dụng. Các điều khoản bổ sung sẽ được ưu tiên áp dụng hơn các Điều khoản này trong trường hợp có xung đột liên quan đến các Dịch vụ được áp dụng.
                    TOHOP có thể sửa đổi các Điều khoản liên quan đến các Dịch vụ tùy từng thời điểm. Các sửa đổi sẽ có hiệu lực khi TOHOP đăng các Điều khoản được cập nhật tại vị trí này hoặc các chính sách sửa đổi hoặc các điều khoản bổ sung về Dịch vụ áp dụng. Nếu bạn tiếp tục truy cập hoặc sử dụng các Dịch vụ sau các bài đăng này, nghĩa là bạn đồng ý chịu sự ràng buộc của các Điều khoản đã được sửa đổi.
                    Việc thu thập và sử dụng thông tin cá nhân liên quan đến các Dịch vụ của chúng tôi được quy định trong Chính sách về Quyền riêng tư của TOHOP tại https://www.tohop.vn/chinh-sach-bao-mat/. TOHOP có thể cung cấp cho nhân viên xử lý yêu cầu bồi thường hoặc doanh nghiệp bảo hiểm mọi thông tin cần thiết (bao gồm thông tin liên lạc của bạn) nếu có yêu cầu bồi thường, tranh chấp hoặc xung đột, có thể bao gồm tai nạn, liên quan đến bạn và một Nhà cung cấp Bên Thứ ba và các thông tin hoặc dữ liệu cần thiết để giải quyết các yêu cầu bồi thường, tranh chấp hoặc xung đột.
                    2. Các dịch vụ
                    3. Sử Dụng Dịch Vụ TOHOP
                    Tài Khoản Người Dùng.
                    Để sử dụng hầu hết các khía cạnh của Dịch vụ, bạn phải đăng ký và duy trì hoạt động một tài khoản Dịch vụ người dùng cá nhân (“Tài khoản”). Bạn phải đủ 18 tuổi trở lên, hoặc đủ tuổi trưởng thành theo pháp lý trong khu vực tài phán của mình (nếu tuổi trưởng thành khác 18 tuổi), để có được một Tài khoản. Việc đăng ký tài khoản yêu cầu bạn phải gửi cho TOHOP các thông tin cá nhân nhất định, chẳng hạn như tên, địa chỉ, số điện thoại di động của bạn và tuổi tác, cũng như tối thiểu một phương thức thanh toán hợp lệ (hoặc thẻ tín dụng hoặc đối tác thanh toán được chấp thuận). Bạn đồng ý duy trì thông tin chính xác, đầy đủ và cập nhật trong Tài khoản của bạn. Việc bạn không duy trì thông tin Tài khoản chính xác, đầy đủ và cập nhật, bao gồm đưa phương thức thanh toán không hợp lệ hoặc hết hạn sử dụng vào trong hồ sơ, có thể dẫn đến việc bạn sẽ không có quyền truy cập và sử dụng Dịch vụ hoặc chấm dứt Thỏa thuận này giữa bạn và TOHOP. Bạn chịu trách nhiệm đối với tất cả các hoạt động diễn ra trong Tài khoản của bạn, và bạn đồng ý duy trì tính an ninh và bảo mật của tên người dùng và mật khẩu Tài khoản của bạn tại mọi thời điểm. Trừ trường hợp được TOHOP cho phép bằng văn bản, bạn chỉ có thể sở hữu một Tài khoản.
                    Yêu Cầu và Ứng Xử của Người Dùng.
                    Các dịch vụ không được cấp cho người dùng dưới 18 tuổi. Bạn không thể uỷ quyền cho bên thứ ba sử dụng Tài khoản của bạn, và bạn không được phép cho người dưới 18 tuổi nhận các dịch vụ vận chuyển hoặc hậu cần từ Nhà cung cấp Bên Thứ ba trừ khi họ đi cùng bạn. Bạn không được chuyển nhượng hoặc chuyển giao Tài khoản của mình cho bất kỳ cá nhân hoặc thực thể pháp lý nào khác. Bạn đồng ý tuân thủ tất cả các luật áp dụng khi sử dụng các Dịch vụ, và bạn chỉ có thể sử dụng Dịch vụ cho các mục đích hợp pháp. Khi sử dụng các dịch vụ, bạn không được gây phiền toái, khó chịu, bất tiện, hoặc thiệt hại tài sản, cho các Nhà cung cấp Bên Thứ ba hoặc bất kỳ bên nào khác. Trong một số trường hợp bạn có thể được yêu cầu cung cấp giấy tờ chứng minh quyền truy cập hoặc sử dụng dịch vụ, và bạn đồng ý rằng bạn có thể bị từ chối truy cập hoặc sử dụng Dịch vụ nếu bạn từ chối cung cấp giấy tờ chứng minh.
                    Mọi hành vi với mục đích lôi kéo khách hàng trên hệ thống của TOHOP đều bị nghiêm cấm. Lôi kéo khách hàng trên hệ thống của TOHOP được hiểu là hành động thương lượng riêng với những Khách Hàng của TOHOP (bao gồm cả Người Giúp Việc hay các Kỹ Thuật Viên) để cung cấp các dịch vụ của TOHOP mà không thông qua hệ thống của TOHOP. TOHOP có quyền từ chối phục vụ hay khóa tài khoản mà không cần báo trước đối với những đối tượng có hành vi trên. Với mỗi Khách Hàng (bao gồm cả Người Giúp Việc hay các Kỹ Thuật Viên), bạn sẽ phải bồi thường cho TOHOP 5.000.000vnđ/01 người.
                    Tin Nhắn Văn Bản.
                    Bằng cách tạo một Tài khoản, bạn đồng ý rằng các Dịch vụ có thể gửi cho bạn tin nhắn văn bản thông báo (SMS) như một phần của hoạt động kinh doanh thông thường của việc sử dụng các Dịch vụ. Bạn có thể chọn không nhận tin nhắn văn bản (SMS) từ TOHOP bất kỳ lúc nào bằng cách gửi email tới tapdoanviet.vn@gmail.com nêu rõ rằng bạn không còn muốn nhận các tin nhắn như vậy, cùng với số điện thoại của thiết bị di động nhận tin nhắn. Bạn công nhận rằng việc chọn không nhận các tin nhắn văn bản (SMS) có thể ảnh hưởng đến việc bạn sử dụng Dịch vụ.
                    Mã Khuyến Mãi.
                    TOHOP có thể tuỳ ý tạo ra các mã khuyến mãi để đổi điểm tín dụng Tài khoản, hoặc các tính năng hoặc lợi ích khác liên quan đến các Dịch vụ này và/hoặc các dịch vụ của một Nhà cung cấp Bên Thứ ba, tùy thuộc vào bất kỳ điều khoản bổ sung nào mà TOHOP thiết lập trên cơ sở từng mã khuyến mãi (“Mã khuyến mãi”). Bạn đồng ý rằng Mã khuyến mãi: (i) phải được sử dụng cho các đối tượng và mục đích dự định, theo cách phù hợp với pháp luật; (ii) không được sao chép, bán hoặc chuyển giao theo bất kỳ cách nào, hoặc cung cấp công khai (cho dù được đăng lên theo hình thức công khai hoặc bất kỳ hình thức nào khác), trừ khi được sự cho phép của TOHOP; (iii) có thể bị TOHOP vô hiệu hóa bất kỳ lúc nào vì bất kỳ lý do gì mà TOHOP không phải chịu trách nhiệm; (iv) chỉ có thể được sử dụng theo các điều khoản cụ thể mà TOHOP thiết lập cho Mã khuyến mãi đó; (v) không có giá trị quy đổi thành tiền mặt; và (vi) có thể hết hạn trước khi bạn sử dụng. TOHOP có quyền giữ lại hoặc khấu trừ các khoản tín dụng, các tính năng hoặc lợi ích khác thu được thông qua việc sử dụng các Mã khuyến mãi của bạn hoặc bất kỳ người dùng nào khác trong trường hợp TOHOP xác định được hoặc tin rằng việc sử dụng hoặc đổi thưởng Mã khuyến mãi có lỗi, gian lận, bất hợp pháp, hoặc vi phạm các điều khoản về Mã khuyến mãi được áp dụng hoặc các Điều khoản này.
                    Nội Dung Người Dùng Cung Cấp.
                    TOHOP có thể tùy ý cho phép bạn gửi, tải lên, công khai hoặc cung cấp cho TOHOP, thông qua các tính năng văn bản, âm thanh và/hoặc hình ảnh của Dịch vụ, các nội dung và thông tin, bao gồm các nhận xét và phản hồi liên quan đến các Dịch vụ, các yêu cầu hỗ trợ, và nộp các thông tin cho các cuộc thi và chương trình khuyến mãi (“Nội dung Người dùng”) tùy từng thời điểm. Mọi Nội dung Người dùng do bạn cung cấp vẫn là tài sản của bạn. Tuy nhiên, bằng cách cung cấp Nội dung Người dùng cho TOHOP, bạn cấp cho TOHOP giấy phép không có bản quyền, không thể thu hồi, chuyển nhượng, sử dụng vĩnh viễn, trên toàn thế giới, với quyền cấp giấy phép con, để sử dụng, sao chép, sửa đổi, tạo ra tác phẩm phái sinh, phân phối, công khai, thực hiện công khai, và khai thác bằng bất kỳ cách nào Nội dung Người dùng trong tất cả các định dạng và các kênh phân phối hiện tại hoặc sau đây được đưa ra (bao gồm liên quan đến các Dịch vụ và hoạt động kinh doanh của TOHOP và trên các trang web và các dịch vụ của bên thứ ba), mà không cần thông báo thêm cho hoặc có được sự đồng ý của bạn, và không yêu cầu bạn hoặc bất kỳ người nào hoặc tổ chức nào khác phải thanh toán.
                    Bạn tuyên bố và đảm bảo rằng: (i) bạn là chủ sở hữu duy nhất và độc quyền tất cả các Nội dung Người dùng hoặc bạn có tất cả các quyền, giấy phép, sự chấp thuận và phát hành cần thiết để cấp cho TOHOP giấy phép Nội dung Người dùng như đã nêu trên; và (ii) Nội dung Người dùng hoặc thông tin bạn nộp, tải lên, công bố hoặc cung cấp Nội dung Người dùng hoặc việc TOHOP sử dụng Nội dung Người dùng như được cho phép bằng văn bản này sẽ không vi phạm, chiếm đoạt, xâm phạm tài sản trí tuệ hoặc các quyền sở hữu hoặc quyền công khai hoặc riêng tư của một bên thứ ba, hoặc dẫn đến hành vi vi phạm pháp luật hoặc quy định áp dụng.
                    Bạn đồng ý không cung cấp Nội dung Người dùng mang tính phỉ báng, bôi nhọ, hận thù, bạo lực, khiêu dâm, tình dục, bất hợp pháp, hoặc gây khó chịu, như được TOHOP tùy ý xác định, bất kể các tài liệu này có thể được pháp luật bảo vệ hay không. TOHOP có thể, nhưng không có nghĩa vụ, rà soát, theo dõi, hoặc xóa Nội dung Người dùng, theo toàn quyền quyết định của TOHOP và vào bất kỳ lúc nào vì bất kỳ lý do nào mà không cần thông báo trước.
                    Truy Cập Mạng và Thiết Bị.
                    Bạn chịu trách nhiệm về việc truy cập mạng dữ liệu cần thiết để sử dụng các Dịch vụ. Mạng dữ liệu di động của bạn và mức phí nhắn tin và có thể áp dụng nếu bạn truy cập hoặc sử dụng các Dịch vụ từ một thiết bị không dây được kích hoạt và bạn phải chịu trách nhiệm về mức giá và phí này. Bạn chịu trách nhiệm thu thập và cập nhật phần cứng tương thích hoặc các thiết bị cần thiết để truy cập và sử dụng các Dịch vụ và Ứng dụng này và bất kỳ bản cập nhật nào. TOHOP không đảm bảo rằng các Dịch vụ, hoặc bất kỳ phần nào trong đó, sẽ hoạt động trên bất kỳ phần cứng hoặc các thiết bị cụ thể nào. Ngoài ra, các Dịch vụ có thể bị trục trặc và chậm trễ vốn thường gặp trong việc sử dụng Internet và các phương tiện liên lạc điện tử.
                    4. Thanh Toán
                    Bạn hiểu rằng việc sử dụng các Dịch vụ có thể phát sinh chi phí cho các dịch vụ hoặc hàng hóa mà bạn nhận được từ một Nhà cung cấp Bên Thứ ba (“Phí”). Sau khi bạn nhận được dịch vụ hoặc hàng hóa thông qua việc sử dụng Dịch vụ, TOHOP sẽ tạo điều kiện thanh toán các khoản Phí được áp dụng thay mặt Nhà cung cấp Bên Thứ ba như đại lý thu nhận thanh toán của Nhà cung cấp Bên Thứ ba. Thanh toán các khoản Phí theo cách này sẽ được coi như thanh toán được bạn thực hiện trực tiếp cho các Nhà cung cấp Bên Thứ ba. Các khoản Phí sẽ bao gồm thuế được áp dụng nếu có yêu cầu của pháp luật. Các khoản Phí mà bạn trả là cuối cùng và không được hoàn lại, trừ trường hợp được TOHOP quyết định. Bạn vẫn có quyền yêu cầu Phí thấp hơn từ một Nhà cung cấp Bên Thứ ba cho các dịch vụ, hàng hóa nhận được từ Nhà cung cấp Bên Thứ ba tại thời điểm nhận dịch vụ, hàng hoá. TOHOP sẽ phản hồi mọi yêu cầu từ Nhà cung cấp Bên Thứ ba để thay đổi Phí cho một dịch vụ hoặc hàng hóa cụ thể.
                    Tất cả các khoản Phí phải trả ngay lập tức và việc thanh toán sẽ được tạo điều kiện bởi TOHOP bằng cách sử dụng phương thức thanh toán ưa thích được chỉ định trong Tài khoản của bạn, sau đó TOHOP sẽ gửi cho bạn một biên nhận qua email, với điều kiện email của bạn đã được xác thực trên Ứng dụng. Nếu phương thức thanh toán Tài khoản chính của bạn được xác định là đã hết hạn, không hợp lệ hoặc không thể tính phí, bạn đồng ý rằng TOHOP có thể, trong vai trò là đại lý thu nhận thanh toán của Nhà cung cấp Bên Thứ ba, sử dụng phương thức thanh toán thứ hai trong Tài khoản của bạn, nếu có.
                    Giữa bạn và TOHOP, TOHOP có quyền tùy ý thiết lập, xóa và/hoặc sửa đổi Phí đối với bất kỳ hoặc tất cả các dịch vụ hoặc hàng hóa nhận được thông qua việc sử dụng Dịch vụ tại bất kỳ thời điểm nào. Hơn nữa, bạn công nhận và đồng ý rằng Phí áp dụng tại các khu vực địa lý nhất định có thể tăng đáng kể trong thời gian nhu cầu cao. TOHOP sẽ nỗ lực thông báo cho bạn về những khoản phí có thể được áp dụng, với điều kiện là bạn sẽ chịu trách nhiệm cho các khoản Phí phát sinh theo Tài khoản của bạn bất kể bạn có biết về các khoản Phí hoặc các khoản tiền đó hay không. Tùy từng thời điểm, TOHOP có thể cung cấp cho người dùng nhất định các chương trình khuyến mãi và giảm giá có thể dẫn đến việc tính phí các khoản tiền khác nhau cho cùng dịch vụ hoặc hàng hóa hay các dịch vụ hoặc hàng hóa tương tự nhận được thông qua việc sử dụng các Dịch vụ này, và bạn đồng ý rằng các chương trình khuyến mãi giảm giá như vậy sẽ không liên quan đến việc bạn sử dụng các Dịch vụ hoặc các khoản Phí áp dụng đối với bạn, trừ khi cũng được cung cấp cho bạn. Bạn có thể chọn hủy bỏ yêu cầu về các dịch vụ hoặc hàng hóa từ một Nhà cung cấp Bên Thứ ba bất kỳ lúc nào trước khi Nhà cung cấp Bên Thứ ba thực hiện dịch vụ, trong trường hợp này bạn có thể phải trả một khoản phí hủy bỏ dịch vụ.
                    Cơ cấu thanh toán này được thiết kế để bù đắp đầy đủ cho các Nhà cung cấp Bên Thứ ba đối với các dịch vụ, hàng hóa được cung cấp. Ngoại trừ đối với dịch vụ vận giúp việc nhà thông qua Ứng dụng, TOHOP không chỉ định bất kỳ phần nào trong thanh toán của bạn làm tiền boa hoặc tiền thưởng cho các Nhà cung cấp Bên Thứ ba. Bất kỳ tuyên bố nào của TOHOP (trên trang web của TOHOP, trong Ứng dụng, hoặc trong các tài liệu tiếp thị của TOHOP) có mục đích nói rằng tiền boa là “tự nguyện”, “không bắt buộc” và/hoặc “được bao gồm” trong các khoản thanh toán của bạn cho các dịch vụ, hàng hóa được cung cấp không có dụng ý cho thấy rằng TOHOP sẽ cung cấp bất kỳ khoản tiền bổ sung nào, ngoài những khoản mô tả ở trên, cho các Nhà cung cấp Bên Thứ ba. Bạn hiểu và đồng ý rằng, khi bạn được tùy ý cung cấp khoản thanh toán bổ sung làm khoản tiền thưởng cho bất kỳ Nhà cung cấp Bên Thứ ba nào cung cấp cho bạn các dịch vụ hoặc hàng hóa nhận được qua Dịch vụ này, bạn không có nghĩa vụ phải làm như vậy. Tiền thưởng là tự nguyện. Sau khi bạn nhận được các dịch vụ hoặc hàng hóa qua Dịch vụ này, bạn sẽ có cơ hội đánh giá trải nghiệm của bạn và để lại phản hồi thêm về Nhà cung cấp Bên Thứ ba.
                    Chi Phí Sửa Chữa hoặc Vệ Sinh.
                    Bạn phải chịu trách nhiệm về các chi phí sửa chữa hư hại, hoặc vệ sinh cần thiết, các phương tiện và tài sản của Nhà cung cấp Bên Thứ ba do việc sử dụng các Dịch vụ theo Tài khoản của bạn vượt quá mức hư hại “hao mòn” bình thường và mức làm sạch cần thiết (“Sửa chữa hoặc Làm sạch”). Trong trường hợp một Nhà cung cấp Bên Thứ ba báo cáo nhu cầu Sửa chữa hoặc Vệ sinh, và yêu cầu Sửa chữa hoặc Vệ sinh đó được TOHOP xác nhận theo toàn quyền hợp lý của mình, TOHOP có quyền tạo điều kiện thanh toán cho các chi phí hợp lý của việc Sửa chữa hoặc Vệ sinh đó thay mặt Nhà cung cấp Bên Thứ ba bằng cách sử dụng phương thức thanh toán được chỉ định trong Tài khoản của bạn. Số tiền này sẽ được TOHOP chuyển đến các Nhà cung cấp Bên Thứ ba và không được hoàn lại.
                    5. Tuyên Bố Miễn Trách; Giới Hạn Trách Nhiệm Pháp Lý; Bồi Thường.
                    TUYÊN BỐ MIỄN TRÁCH.
                    CÁC DỊCH VỤ ĐƯỢC CUNG CẤP “NGUYÊN TRẠNG” VÀ “NHƯ SẴN CÓ”. TOHOP KHƯỚC TỪ MỌI TUYÊN BỐ VÀ BẢO ĐẢM, RÕ RÀNG, NGỤ Ý HOẶC THEO LUẬT ĐỊNH, KHÔNG ĐƯỢC NÊU RÕ TRONG NHỮNG ĐIỀU KHOẢN NÀY, BAO GỒM CÁC BẢO ĐẢM VỀ KHẢ NĂNG THƯƠNG MẠI, TÍNH PHÙ HỢP CHO MỘT MỤC ĐÍCH CỤ THỂ VÀ KHÔNG VI PHẠM PHÁP LUẬT. NGOÀI RA, TOHOP KHÔNG ĐƯA RA TUYÊN BỐ, BẢO HÀNH, BẢO ĐẢM VỀ TÍNH TIN CẬY, TÍNH KỊP THỜI, CHẤT LƯỢNG, TÍNH PHÙ HỢP HOẶC SẴN CÓ CỦA CÁC DỊCH VỤ NÀY, CÁC DỊCH VỤ HOẶC HÀNG HÓA ĐƯỢC YÊU CẦU QUA VIỆC SỬ DỤNG DỊCH VỤ NÀY, HOẶC CÁC DỊCH VỤ NÀY SẼ KHÔNG BỊ GIÁN ĐOẠN HOẶC KHÔNG CÓ LỖI. TOHOP KHÔNG ĐẢM BẢO CHẤT LƯỢNG, TÍNH PHÙ HỢP, AN TOÀN HOẶC NĂNG LỰC CỦA NHÀ CUNG CẤP BÊN THỨ BA. BẠN ĐỒNG Ý CHỊU TRÁCH NHIỆM VỀ TOÀN BỘ RỦI RO PHÁT SINH BÊN NGOÀI VIỆC SỬ DỤNG CÁC DỊCH VỤ NÀY VÀ BẤT KỲ DỊCH VỤ HOẶC HÀNG HÓA ĐƯỢC YÊU CẦU NÀO CÓ LIÊN QUAN, TRONG PHẠM VI TỐI ĐA PHÁP LUẬT ÁP DỤNG CHO PHÉP.
                    GIỚI HẠN TRÁCH NHIỆM PHÁP LÝ.
                    TOHOP SẼ KHÔNG CHỊU TRÁCH NHIỆM VỀ CÁC THIỆT HẠI MANG TÍNH GIÁN TIẾP, NGẪU NHIÊN, ĐẶC BIỆT, CẢNH CÁO, TRỪNG TRỊ HOẶC HẬU QUẢ, BAO GỒM TỔN THẤT VỀ LỢI NHUẬN, TỔN THẤT VỀ DỮ LIỆU, THƯƠNG TÍCH CÁ NHÂN HOẶC THIỆT HẠI VỀ TÀI SẢN, LIÊN QUAN, HOẶC PHÁT SINH TỪ VIỆC SỬ DỤNG CÁC DỊCH VỤ, NGAY CẢ NẾU TOHOP ĐÃ ĐƯỢC CẢNH BÁO VỀ NGUY CƠ CỦA CÁC THIỆT HẠI NHƯ VẬY. TOHOP SẼ KHÔNG CHỊU TRÁCH NHIỆM CHO BẤT KỲ THIỆT HẠI, TRÁCH NHIỆM HOẶC TỔN THẤT NÀO PHÁT SINH DO: (i) VIỆC BẠN SỬ DỤNG HOẶC DỰA TRÊN CÁC DỊCH VỤ HOẶC BẠN KHÔNG CÓ QUYỀN TRUY CẬP HOẶC SỬ DỤNG DỊCH VỤ; HOẶC (ii) MỌI GIAO DỊCH HOẶC QUAN HỆ GIỮA BẠN VÀ NHÀ CUNG CẤP BÊN THỨ BA, NGAY CẢ NẾU TOHOP ĐÃ ĐƯỢC CẢNH BÁO VỀ NGUY CƠ CỦA CÁC THIỆT HẠI NHƯ VẬY. TOHOP SẼ KHÔNG CHỊU TRÁCH NHIỆM VỀ VIỆC TRÌ HOÃN HOẶC KHÔNG HOẠT ĐỘNG DO CÁC NGUYÊN NHÂN NẰM NGOÀI KHẢ NĂNG KIỂM SOÁT CỦA TOHOP. BẠN CÔNG NHẬN RẰNG NHÀ CUNG CẤP DỊCH VỤ BÊN THỨ BA CUNG CẤP CÁC DỊCH VỤ ĐƯỢC YÊU CẦU QUA MỘT SỐ THƯƠNG HIỆU YÊU CẦU CÓ THỂ CUNG CẤP DỊCH VỤ DÙNG CHUNG HOẶC KHÁCH HÀNG ĐỒNG CẤP VÀ CÓ THỂ KHÔNG ĐƯỢC CẤP PHÉP HOẶC CHO PHÉP HOẠT ĐỘNG MỘT CÁCH CHUYÊN NGHIỆP. TRONG MỌI TRƯỜNG HỢP TOHOP KHÔNG CHỊU TRÁCH NHIỆM PHÁP LÝ ĐỐI VỚI BẠN LIÊN QUAN TỚI CÁC DỊCH VỤ VỀ MỌI THIỆT HẠI, TỔN THẤT VÀ CÁC NGUYÊN NHÂN TỐ TỤNG.
                    BẠN CÓ THỂ SỬ DỤNG DỊCH VỤ CỦA TOHOP ĐỂ YÊU CẦU VÀ LÊN LỊCH DỊCH VỤ GIÚP VIỆC NHÀ VÀ/HOẶC BẢO TRÌ MÁY LẠNH VỚI NHÀ CUNG CẤP BÊN THỨ BA, NHƯNG BẠN ĐỒNG Ý RẰNG TOHOP KHÔNG CÓ TRÁCH NHIỆM HOẶC NGHĨA VỤ VỚI BẠN LIÊN QUAN ĐẾN BẤT KỲ DỊCH VỤ GIÚP VIỆC NHÀ VÀ/HOẶC BẢO TRÌ MÁY LẠNH NÀO ĐƯỢC NHÀ CUNG CẤP BÊN THỨ BA CUNG CẤP CHO BẠN TRỪ CÁC TRÁCH NHIỆM ĐƯỢC QUY ĐỊNH RÕ TRONG CÁC ĐIỀU KHOẢN NÀY.
                    CÁC GIỚI HẠN VÀ TUYÊN BỐ MIỄN NHIỆM TRONG PHẦN 5 NÀY KHÔNG NHẰM GIỚI HẠN TRÁCH NHIỆM HOẶC THAY THẾ CÁC QUYỀN CỦA NGƯỜI TIÊU DÙNG KHÔNG THỂ LOẠI TRỪ THEO PHÁP LUẬT.
                    Bồi Thường.
                    Bạn đồng ý bồi thường và giữ cho TOHOP và các cán bộ, giám đốc, nhân viên và đại lý vô hại khỏi bất kỳ và tất cả các yêu cầu bồi thường, yêu cầu, trách nhiệm pháp lý, và các chi phí (bao gồm chi phí luật sư) phát sinh từ hoặc liên quan đến: (i) bạn sử dụng các Dịch vụ này, dịch vụ hoặc các sản phẩm nhận được thông qua việc sử dụng các Dịch vụ này; (ii) bạn phá vỡ hoặc vi phạm các Điều khoản này; (iii) TOHOP sử dụng Nội dung Người dùng; hoặc (iv) bạn vi phạm các quyền của bất kỳ bên thứ ba nào, bao gồm Nhà cung cấp Bên Thứ ba.
                    6. Các Quy Định Khác
                    Yêu cầu bồi thường Vi phạm Bản quyền.
                    Yêu cầu bồi thường vi phạm bản quyền phải được gửi đến đại lý được chỉ định của TOHOP. Vui lòng truy cập trang web của TOHOP tại https://www.tohop.vn/lien-he/ để biết địa chỉ được chỉ định và thông tin bổ sung.
                    Thông Báo.
                    TOHOP có thể đưa ra thông báo bằng phương thức thông báo chung về các Dịch vụ, gửi thư điện tử đến địa chỉ email trong Tài khoản của bạn, hoặc thông qua văn bản liên lạc được gửi qua đường bưu điện đến địa chỉ được ghi trong Tài khoản của bạn. Bạn có thể thông báo cho TOHOP bằng văn bản liên lạc đến địa chỉ văn phòng của TOHOP tại LK15, Phan Đình Giót, Văn Khê, Hà Đông, Hà Nội, Việt Nam, Việt Nam.
                    Điều Khoản Chung.
                    Bạn không thể chuyển nhượng hoặc chuyển giao các Điều khoản này, toàn bộ hoặc một phần, mà không có sự chấp thuận trước bằng văn bản của TOHOP. Bạn chấp thuận cho TOHOP quyền chuyển nhượng hoặc chuyển giao các Điều khoản này, toàn bộ hoặc một phần, cho: (i) một công ty con hoặc chi nhánh; (ii) ngân hàng thanh toán vốn chủ sở hữu, doanh nghiệp hoặc tài sản của TOHOP; hoặc (iii) bên kế thừa do sáp nhập. Không có mối quan hệ liên doanh, hợp tác, làm việc hoặc đại lý tồn tại giữa bạn, TOHOP hoặc bất kỳ Nhà cung cấp Bên Thứ ba nào như là kết quả của hợp đồng giữa bạn và TOHOP hoặc việc sử dụng các Dịch vụ.
                    Nếu bất kỳ điều khoản nào trong các Điều khoản này được coi là phi pháp, không có hiệu lực hoặc không thể thực hiện, toàn bộ hoặc một phần, thì điều khoản hoặc phần đó, theo bất kỳ quy định nào của pháp luật, trong phạm vi đó sẽ không được coi là một phần của Điều khoản này nhưng tính hợp pháp, tính hiệu lực và khả năng thực thi của các điều khoản còn lại trong các Điều khoản này sẽ không bị ảnh hưởng. Trong trường hợp đó, các bên sẽ thay thế điều khoản hoặc phần của điều khoản phi pháp, không có hiệu lực hoặc không thể thực hiện được bằng một điều khoản hoặc phần điều khoản hợp pháp, có hiệu lực và có thể thực thi ở mức tối đa nhất có thể, có hiệu lực tương tự như điều khoản hoặc phần của điều khoản phi pháp, không có hiệu lực hoặc không thể thực thi, bất kể nội dung và mục đích của các Điều khoản này là gì. Các Điều khoản này tạo thành toàn bộ thỏa thuận và biên bản ghi nhớ của các bên liên quan đến nội dung chính và các sửa đổi, thay thế đối với các thỏa thuận hoặc các cam kết hiện hành hoặc trước đó liên quan tới nội dung chính. Trong các Điều khoản này, từ ''bao gồm'' nghĩa là ''bao gồm, nhưng không giới hạn.”
                    7. Chính sách hoàn tiền
                    Khi nào tôi sẽ được hoàn lại đầy đủ số tiền ?
                    - Hủy trước 10 phút đăng việc
                    - Người giúp việc chủ động đề nghị hủy vì lý do chính đáng
                    - Sau 1 giờ bạn đăng việc mà không có ai nhận (Chỉ áp dụng trong ngày).
                    - Nếu đến giờ mà người giúp việc không đến, bạn phải báo với TOHOP. Thời gian cho phép báo hủy là 30 phút sau thời gian bạn đã đặt và trước khi kết thúc công việc.
                    Ví dụ: Nếu bạn đăng việc lúc 15:00, công việc thực hiện trong 2h. Thời gian cho phép báo hủy là từ 15:30 đến 17:00 cùng ngày. Bất cứ yêu cầu hủy việc ngoài khoảng thời gian sẽ không có hiệu lực.
                    Trong tất cả trường hợp trên, bạn sẽ không bị tính phí cho yêu cầu hủy.
                    Nếu bạn thanh toán bằng thẻ tín dụng thì phần tiền hoàn lại sẽ được chuyển lại vào tài khoản của bạn trong vòng 15’.
                    Khi nào tôi có thể được hoàn lại một phần tiền ?
                    - Hủy sau 10 phút đăng công việc (20.000 VND phí lần hủy đầu tiên) - Khi bạn nhấn vào nút hủy, chúng tôi sẽ báo lại cho bạn về mức phí 20.000 VND trước khi bạn xác nhận hủy.
                    Khi nào tôi không đủ điều kiện được hoàn tiền ?
                    - Khi người giúp việc dọn dẹp không đạt tiêu chuẩn của bạn (Trong trường hợp này vui lòng liên hệ với đường dây hỗ trợ của chúng tôi) - Khi bạn báo hủy sau khi đã qua giờ đăng làm việc
                    Cách yêu cầu hoàn lại tiền
                    - Để hủy bỏ lịch đăng việc, vui lòng sử dụng tính năng hủy bỏ trong ứng dụng. - Đối với các tình huống khác, vui lòng liên hệ với bộ phận hỗ trợ khách hàng của chúng tôi qua email: tapdoanviet.vn@gmail.com

                </Text>

            </ScrollView>
            
        )

    }
}
export default DieuKhoan;