# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TapDoanViet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TapDoanViet
pod 'Firebase/Messaging'


  target 'TapDoanViet-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

    pod 'react-native-video', :path => '../node_modules/react-native-video'

  end

  target 'TapDoanVietTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TapDoanViet-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TapDoanViet-tvOS



end
